[2015-02-10 06:48:46] local.ERROR: exception 'InvalidArgumentException' with message 'Command "auth:controller" is not defined.

Did you mean one of these?
    make:controller
    auth:clear-resets' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php:549
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(192): Symfony\Component\Console\Application->find('auth:controller')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  
[2015-02-10 06:56:19] local.ERROR: exception 'ReflectionException' with message 'Class UserTableSeeder does not exist' in C:\xampp\htdocs\laravel\storage\framework\compiled.php:1026
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1026): ReflectionClass->__construct('UserTableSeeder')
#1 C:\xampp\htdocs\laravel\storage\framework\compiled.php(977): Illuminate\Container\Container->build('UserTableSeeder', Array)
#2 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1476): Illuminate\Container\Container->make('UserTableSeeder', Array)
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(55): Illuminate\Foundation\Application->make('UserTableSeeder')
#4 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(37): Illuminate\Database\Seeder->resolve('UserTableSeeder')
#5 C:\xampp\htdocs\laravel\database\seeds\DatabaseSeeder.php(17): Illuminate\Database\Seeder->call('UserTableSeeder')
#6 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(57): DatabaseSeeder->run()
#7 [internal function]: Illuminate\Database\Console\SeedCommand->fire()
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(922): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#10 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}  
[2015-02-10 06:57:22] local.ERROR: exception 'ReflectionException' with message 'Class UserTableSeeder does not exist' in C:\xampp\htdocs\laravel\storage\framework\compiled.php:1026
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1026): ReflectionClass->__construct('UserTableSeeder')
#1 C:\xampp\htdocs\laravel\storage\framework\compiled.php(977): Illuminate\Container\Container->build('UserTableSeeder', Array)
#2 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1476): Illuminate\Container\Container->make('UserTableSeeder', Array)
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(55): Illuminate\Foundation\Application->make('UserTableSeeder')
#4 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(37): Illuminate\Database\Seeder->resolve('UserTableSeeder')
#5 C:\xampp\htdocs\laravel\database\seeds\DatabaseSeeder.php(17): Illuminate\Database\Seeder->call('UserTableSeeder')
#6 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(57): DatabaseSeeder->run()
#7 [internal function]: Illuminate\Database\Console\SeedCommand->fire()
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(922): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#10 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}  
[2015-02-10 06:58:17] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 06:59:14] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 06:59:25] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 07:00:18] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 07:00:30] local.ERROR: exception 'ReflectionException' with message 'Class UserTableSeeder does not exist' in C:\xampp\htdocs\laravel\storage\framework\compiled.php:1026
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1026): ReflectionClass->__construct('UserTableSeeder')
#1 C:\xampp\htdocs\laravel\storage\framework\compiled.php(977): Illuminate\Container\Container->build('UserTableSeeder', Array)
#2 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1476): Illuminate\Container\Container->make('UserTableSeeder', Array)
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(55): Illuminate\Foundation\Application->make('UserTableSeeder')
#4 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(37): Illuminate\Database\Seeder->resolve('UserTableSeeder')
#5 C:\xampp\htdocs\laravel\database\seeds\DatabaseSeeder.php(17): Illuminate\Database\Seeder->call('UserTableSeeder')
#6 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(57): DatabaseSeeder->run()
#7 [internal function]: Illuminate\Database\Console\SeedCommand->fire()
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(922): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#10 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}  
[2015-02-10 07:04:12] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 07:06:18] local.ERROR: exception 'ReflectionException' with message 'Class UserTableSeeder does not exist' in C:\xampp\htdocs\laravel\storage\framework\compiled.php:1026
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1026): ReflectionClass->__construct('UserTableSeeder')
#1 C:\xampp\htdocs\laravel\storage\framework\compiled.php(977): Illuminate\Container\Container->build('UserTableSeeder', Array)
#2 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1476): Illuminate\Container\Container->make('UserTableSeeder', Array)
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(55): Illuminate\Foundation\Application->make('UserTableSeeder')
#4 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(37): Illuminate\Database\Seeder->resolve('UserTableSeeder')
#5 C:\xampp\htdocs\laravel\database\seeds\DatabaseSeeder.php(17): Illuminate\Database\Seeder->call('UserTableSeeder')
#6 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(57): DatabaseSeeder->run()
#7 [internal function]: Illuminate\Database\Console\SeedCommand->fire()
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(922): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#10 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}  
[2015-02-10 07:07:44] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 07:07:54] local.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'' in C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:358
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(358): PDO->prepare('insert into `us...')
#1 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(606): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(570): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(359): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(316): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `us...', Array)
#6 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1717): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(948): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9720): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9720): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9710): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9667): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9307): Illuminate\Database\Eloquent\Model->save()
#14 C:\xampp\htdocs\laravel\database\seeds\UserTableSeeder.php(17): Illuminate\Database\Eloquent\Model::create(Array)
#15 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(37): UserTableSeeder->run()
#16 C:\xampp\htdocs\laravel\database\seeds\DatabaseSeeder.php(17): Illuminate\Database\Seeder->call('UserTableSeeder')
#17 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(57): DatabaseSeeder->run()
#18 [internal function]: Illuminate\Database\Console\SeedCommand->fire()
#19 C:\xampp\htdocs\laravel\storage\framework\compiled.php(922): call_user_func_array(Array, Array)
#20 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#21 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: insert into `users` (`name`, `username`, `email`, `password`, `updated_at`, `created_at`) values (Andri Riantana, seputarpemrograman, seputarpemrograman@gmail.com, y$ZXPPPxJfDvXKh.11kDWZdOE/1FHV2rhaBUHjmRxbUxkUWekCArwGS, 2015-02-10 07:07:54, 2015-02-10 07:07:54))' in C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:614
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(570): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(359): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php(316): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1717): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(948): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9720): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9720): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9710): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9667): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 C:\xampp\htdocs\laravel\storage\framework\compiled.php(9307): Illuminate\Database\Eloquent\Model->save()
#12 C:\xampp\htdocs\laravel\database\seeds\UserTableSeeder.php(17): Illuminate\Database\Eloquent\Model::create(Array)
#13 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(37): UserTableSeeder->run()
#14 C:\xampp\htdocs\laravel\database\seeds\DatabaseSeeder.php(17): Illuminate\Database\Seeder->call('UserTableSeeder')
#15 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(57): DatabaseSeeder->run()
#16 [internal function]: Illuminate\Database\Console\SeedCommand->fire()
#17 C:\xampp\htdocs\laravel\storage\framework\compiled.php(922): call_user_func_array(Array, Array)
#18 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#19 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}  
[2015-02-10 07:13:11] local.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php:181
Stack trace:
#0 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('Seeded:UserTabl...')
#1 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Input\Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(225): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\laravel\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\laravel\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2015-02-10 07:23:36] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'HTML' not found' in C:\xampp\htdocs\laravel\storage\framework\views\95f1ef49e18583f0e6d3a48b83cb9bef:5
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:23:48] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'HTML' not found' in C:\xampp\htdocs\laravel\storage\framework\views\95f1ef49e18583f0e6d3a48b83cb9bef:5
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:23:49] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'HTML' not found' in C:\xampp\htdocs\laravel\storage\framework\views\95f1ef49e18583f0e6d3a48b83cb9bef:5
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:25:09] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'HTML' not found' in C:\xampp\htdocs\laravel\storage\framework\views\95f1ef49e18583f0e6d3a48b83cb9bef:5
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:25:10] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'HTML' not found' in C:\xampp\htdocs\laravel\storage\framework\views\95f1ef49e18583f0e6d3a48b83cb9bef:5
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:25:11] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'HTML' not found' in C:\xampp\htdocs\laravel\storage\framework\views\95f1ef49e18583f0e6d3a48b83cb9bef:5
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:33:46] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\Auth' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:68
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:34:36] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\Redirect' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:71
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:35:19] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:43
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:36:16] local.ERROR: exception 'InvalidArgumentException' with message 'View [login] not found.' in C:\xampp\htdocs\laravel\storage\framework\compiled.php:12795
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(12768): Illuminate\View\FileViewFinder->findInPaths('login', Array)
#1 C:\xampp\htdocs\laravel\storage\framework\compiled.php(12893): Illuminate\View\FileViewFinder->find('login')
#2 C:\xampp\htdocs\laravel\storage\framework\compiled.php(5221): Illuminate\View\Factory->make('login')
#3 C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php(44): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php(44): Illuminate\Support\Facades\View::make('login')
#5 [internal function]: App\Http\Controllers\HomeController->login()
#6 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8204): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8271): Illuminate\Routing\Controller->callAction('login', Array)
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8250): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), 'login')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8866): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel\app\Http\Middleware\Authenticate.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8849): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8237): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
#17 C:\xampp\htdocs\laravel\storage\framework\compiled.php(7234): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#18 C:\xampp\htdocs\laravel\storage\framework\compiled.php(7205): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6871): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8866): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8849): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6872): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6861): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6846): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1884): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8866): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\laravel\storage\framework\compiled.php(2380): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\laravel\app\Http\Middleware\VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\xampp\htdocs\laravel\storage\framework\compiled.php(11989): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\laravel\storage\framework\compiled.php(10695): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\xampp\htdocs\laravel\storage\framework\compiled.php(11695): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\xampp\htdocs\laravel\storage\framework\compiled.php(11644): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\laravel\storage\framework\compiled.php(2418): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8849): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1862): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1852): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 C:\xampp\htdocs\laravel\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}  
[2015-02-10 07:36:26] local.ERROR: exception 'InvalidArgumentException' with message 'View [login] not found.' in C:\xampp\htdocs\laravel\storage\framework\compiled.php:12795
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(12768): Illuminate\View\FileViewFinder->findInPaths('login', Array)
#1 C:\xampp\htdocs\laravel\storage\framework\compiled.php(12893): Illuminate\View\FileViewFinder->find('login')
#2 C:\xampp\htdocs\laravel\storage\framework\compiled.php(5221): Illuminate\View\Factory->make('login')
#3 C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php(44): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php(44): Illuminate\Support\Facades\View::make('login')
#5 [internal function]: App\Http\Controllers\HomeController->login()
#6 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8204): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8271): Illuminate\Routing\Controller->callAction('login', Array)
#8 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8250): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), 'login')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8866): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel\app\Http\Middleware\Authenticate.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8849): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8237): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
#17 C:\xampp\htdocs\laravel\storage\framework\compiled.php(7234): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#18 C:\xampp\htdocs\laravel\storage\framework\compiled.php(7205): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6871): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8866): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8849): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6872): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6861): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\laravel\storage\framework\compiled.php(6846): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1884): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8866): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\laravel\storage\framework\compiled.php(2380): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\laravel\app\Http\Middleware\VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\xampp\htdocs\laravel\storage\framework\compiled.php(11989): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\laravel\storage\framework\compiled.php(10695): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\xampp\htdocs\laravel\storage\framework\compiled.php(11695): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\xampp\htdocs\laravel\storage\framework\compiled.php(11644): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\laravel\storage\framework\compiled.php(2418): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8858): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\xampp\htdocs\laravel\storage\framework\compiled.php(8849): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1862): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1852): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 C:\xampp\htdocs\laravel\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}  
[2015-02-10 07:39:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:43
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:40:10] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:43
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:40:38] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:43
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:41:08] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:43
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-02-10 07:41:55] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\View' not found' in C:\xampp\htdocs\laravel\app\Http\Controllers\HomeController.php:43
Stack trace:
#0 C:\xampp\htdocs\laravel\storage\framework\compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
